inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/spring
    - config/application.rb
    - config/initializers/*
    - config/environments/*
    - db/migrate/20160531175300_devise_create_users.rb
    - db/schema.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false
