language: ruby
rvm:
  - 2.2.0

services:
  - postgresql

before_install:
  - gem update --remote bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rspec
  - rubocop
  - rubocop -R
