language: ruby
rvm:
  - 2.2.0

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec rubocop -R --config .rubocop.yml
